### 로그인 API
POST http://localhost:3001/auth/login
Content-Type: application/json
Authorization: Basic dGVzdEBjb2RlZmFjdG9yeS5haTp0ZXN0dGVzdA==

### token refresh
POST http://localhost:3000/auth/token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAY29kZWZhY3RvcnkuYWkiLCJzdWIiOiJmNTViMzJkMi00ZDY4LTRjMWUtYTNjYS1kYTlkN2QwZDkyZTUiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTcxMzY5NzkwMCwiZXhwIjoxNzEzNzg0MzAwfQ.hD_rCQHGIuU6nKl8gdULcPs5N_xt0nrVoibWqVXJZY8

### restaurant
GET http://ia.jung.mock.pe.kr:3001/restaurant?count=20&after=
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAY29kZWZhY3RvcnkuYWkiLCJzdWIiOiJmNTViMzJkMi00ZDY4LTRjMWUtYTNjYS1kYTlkN2QwZDkyZTUiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzEzODU2MzE3LCJleHAiOjE3MTM4NTY2MTd9.MR_1hAMRFxNhpf7-BCYhtjW1VZ0IOqIDxoLoptIuIJM

### restaurant show
GET http://ia.jung.mock.pe.kr:3001/restaurant/5ac83bfb-f2b5-55f4-be3c-564be3f01a5b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAY29kZWZhY3RvcnkuYWkiLCJzdWIiOiJmNTViMzJkMi00ZDY4LTRjMWUtYTNjYS1kYTlkN2QwZDkyZTUiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzEzODYyNjc4LCJleHAiOjE3MTM4NjI5Nzh9.vuRUNUcQP-j2I45uKV6ql3XcBSza-rdc19yKp2beZ54

### user me
GET http://localhost:3000/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOiJmNTViMzJkMi00ZDY4LTRjMWUtYTNjYS1kYTlkN2QwZDkyZTQiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzE1MDAwNjg5LCJleHAiOjE3MTUwMDA5ODl9.CCK3R4xfSyYxkjz5gd5foTJcY4rSTc82pFI6GGFIkbs