### rating list TEST
GET http://localhost:3000/restaurant/5ac83bfb-f2b5-55f4-be3c-564be3f01a5b/rating?count=20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOiJmNTViMzJkMi00ZDY4LTRjMWUtYTNjYS1kYTlkN2QwZDkyZTQiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzE0OTI2NjE0LCJleHAiOjE3MTQ5MjY5MTR9.TCbvA7DTCgzdRYWKkFl4miVzGN4uZjCCY3XxgCxVHLk